---
# roles/aws.teardown/tasks/00_vms.yml

- name: Gather EC2 facts
  ec2_remote_facts:
    region: "{{ aws_region }}"
    filters:
      "tag:namespace": "{{ namespace }}"
  register: ec2_facts

- name: Unsubscribe VMs
  include: unregister-vm.yml public_ip={{ item.public_ip_address }}
  with_items: "{{ ec2_facts.instances }}"
  when: ((platform == 'openshift-enterprise') and (item.state == 'running'))
  ignore_errors: yes

- name: Notify of VMs that could not be unsubscribed
  debug:
    msg: "The VM {{ item.private_dns_name }} could not be unsubscribed because it was stopped."
  with_items: "{{ ec2_facts.instances }}"
  when: ((platform == 'openshift-enterprise') and (item.state == 'stopped'))
  ignore_errors: yes

- name: Disassociate elastic IP
  ec2_eip:
    device_id: "{{item.id}}"
    ip: "{{item.public_ip_address}}"
    region: "{{ aws_region }}"
    state: absent
  with_items: "{{ ec2_facts.instances }}"
  when: (item.tags.Name == '{{ ec2_master_tag }}') and
        (item.tags.namespace == '{{ namespace }}') and
        (item.state != 'terminated')

- name: Terminate EC2 VMs
  ec2:
    state: absent
    region: "{{ aws_region }}"
    instance_ids: "{{ item.id }}"
    wait: yes
  with_items: "{{ ec2_facts.instances }}"
  when: item.state != 'terminated'
