---
# roles/aws.teardown/tasks/00_vms.yml

- name: Create VPC
  ec2_vpc_net_facts:
   region: "{{ aws_region }}"
   filters:
     "tag:Name": "{{ vpc_tag }}"
  register: vpc_facts

- name: Remove subnets and route tables from VPC
  local_action:
    module: ec2_vpc
    vpc_id: "{{ item.id }}"
    region: "{{ aws_region }}"
    state: present
    resource_tags: "{}"
    subnets: []
    internet_gateway: False
    route_tables: []
    wait: yes
  with_items: "{{ vpc_facts.vpcs }}"

- name: Delete VPC
  ec2_vpc_net:
   name: "{{ vpc_tag }}"
   cidr_block: "{{ vpc_cidr_block }}"
   region: "{{ aws_region }}"
   state: "absent"
   aws_access_key: "{{ aws_access_key }}"
   aws_secret_key: "{{ aws_secret_key }}"
   tags:
    Name: "{{ vpc_tag }}"
    namespace: "{{ namespace }}"
