---

- name: Enable required repos
  shell: 'subscription-manager repos --enable="rhel-7-server-ose-{{ version }}-rpms" --enable="rhel-7-fast-datapath-rpms"'
  retries: 5
  delay: 10
  become: true

- name: Install baseline packages
  yum:
    name:
      - "wget"
      - "git"
      - "net-tools"
      - "bind-utils"
      - "iptables-services"
      - "bridge-utils"
      - "bash-completion"
      - "kexec-tools"
      - "sos"
      - "psacct"
      - "docker-1.12.6"
    state: "present"
  become: true
